"""add one item

Revision ID: ea916f4d911f
Revises: 77aaee4cb9f8
Create Date: 2023-04-21 20:29:24.760716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea916f4d911f'
down_revision = '77aaee4cb9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('inventory_quantity')

    # ### end Alembic commands ###
